### ISSUE TITLE
Merge and make this a team effort?

### ISSUE THREAD

**Issue by pichfl** [sindresorhus/electron-serve#1]
Hi Sindre,

I maintain a rather similar module, which is in use for ember-electron: https://github.com/pichfl/electron-protocol-serve 

Maybe we can combine our efforts?

**Comment by sindresorhus** [comment]
This module is pretty much done, so there's not going to be much effort. And I don't think merging is going to work out, as I'm not really interested in changing anything, and successful merging usually requires compromise. Choice is good though, and now users can choose which one they prefer :)
