### ISSUE TITLE
Using it with electron builder ?

### ISSUE THREAD

**Issue by x4080** [sindresorhus/electron-serve#31]
Hi, I try to build using electron builder, and after build, it seems cannot open the 'app://-' location, is it because the
"build" folder that contains single-page web app files is not accessible ?

My electron builder config :
```
  ...
  "build": {
    "extraFiles": [
      "build"
    ],
  ...
```

the "build" folder is the single-page web app folder

Anybody has clue ?

Thanks

**Comment by x4080** [comment]
Found the cause : cannot use build folder name for static files

**Comment by trungleduc** [comment]
Hi @x4080, i'm having the same issue, could you share your setup to make it work with electron builder?
