### ISSUE TITLE
Unclear sentence in readme

### ISSUE THREAD

**Issue by mhkeller** [sindresorhus/electron-serve#38]
> The [partition](https://electronjs.org/docs/api/session#sessionfrompartitionpartition-options) the protocol should be installed to, if you're not using Electron's default partition.

It looks like there's a duplicate subject here and the wrong "to". Should this read: "**The partition** should be installed **too**"?

**Comment by sindresorhus** [comment]
No, the existing sentence is correct, although I guess it could be clearer.

**Comment by mhkeller** [comment]
Ah got it. Yes that’s clearer now. Thanks.
