### ISSUE TITLE
looks like it doesn't handle asar files?

### ISSUE THREAD

**Issue by InputNeuron** [sindresorhus/electron-serve#6]
Just local directories?  This means packaged apps won't work though...

**Comment by sindresorhus** [comment]
Have you actually tried it or are you just assuming? I'm using this module in multiple production apps with ASAR.

**Comment by InputNeuron** [comment]
these were questions not statements ;)

**Comment by sindresorhus** [comment]
All the Node.js `fs` methods are patched for ASAR in Electron and works like normal. So there's nothing special needed to support ASAR.

**Comment by customautosys** [comment]
I am facing the same problem. When my app is built using electron builder, I get a File Not Found error unless I set asar:false. It appears that when ASAR is built, app.getAppPath is returning an empty string for some strange reason.

**Comment by ibash** [comment]
@siauderman late to the game, what are you setting the directory to?

If you're setting it to the top level like: `serve({ directory: '.' })`

There's a bug where no path is doesn't serve `index.html` for `app://-`

```
// filePath = "...Contents/Resources/app.asar"
// so path.extname(filePath) === ".asar" and it serves file not found

if (resolvedPath || !path.extname(filePath) || path.extname(filePath) === '.html') {
```

**Comment by customautosys** [comment]
> 
> 
> @siauderman late to the game, what are you setting the directory to?
> 
> If you're setting it to the top level like: `serve({ directory: '.' })`
> 
> There's a bug where no path is doesn't serve `index.html` for `app://-`
> 
> ```
> // filePath = "...Contents/Resources/app.asar"
> // so path.extname(filePath) === ".asar" and it serves file not found
> 
> if (resolvedPath || !path.extname(filePath) || path.extname(filePath) === '.html') {
> ```

so instead of `serve({ directory: '.' })`, what should I be doing?

**Comment by ibash** [comment]
Oh, I think `directory: '.'` should work, made a PR that fixes it: https://github.com/sindresorhus/electron-serve/pull/26

You could point your package.json to `ibash/electron-serve` in the meantime.
