### ISSUE TITLE
Benefits of using electron-serve in Angular

### ISSUE THREAD

**Issue by bampakoa** [sindresorhus/electron-serve#8]
Hi,

I am currently developing an Electron application that renders an Angular application using standard `win.loadURL('file://…')`. It uses the router module from Angular internally for routing tasks and it works ok. What is the advantage of using this library over the standard approach?

Thanks

**Comment by sindresorhus** [comment]
I don't know anything about Angular development, but I assume the router module is using hashbang instead of real URLs then? That might come with certain downsides.

For example, in the React world, the downsides are:

> IMPORTANT NOTE: Hash history does not support location.key or location.state. In previous versions we attempted to shim the behavior but there were edge-cases we couldn't solve. Any code or plugin that needs this behavior won't work. As this technique is only intended to support legacy browsers, we encourage you to configure your server to work with <BrowserHistory> instead.
> \- https://github.com/ReactTraining/react-router/blob/master/packages/react-router-dom/docs/api/HashRouter.md

**Comment by bampakoa** [comment]
@sindresorhus :pray: for the clarification.
